preload = /home/noah/Pictures/wallpapers/main.png
preload = /home/noah/Pictures/wallpapers/vertical.png

wallpaper = HDMI-A-1,/home/noah/Pictures/wallpapers/main.png
wallpaper = DP-1,/home/noah/Pictures/wallpapers/vertical.png

splash = false
ipc = true
